### PR TITLE
Export names from global class or id

### PR DESCRIPTION
**Pull request by david-zw-liu**
Hi, 
I made this change to export global class name or id name. 
Because our project used `css-loader` with `local` mode without hash before.
Now I want to switch mode to `global` mode and keep using `styles.className` to reference class name in imported styles.

Please help checking whether this PR hurts any backwards compatibility.

Thanks.

Related issue:
https://github.com/webpack-contrib/css-loader/issues/258

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Good job! We need an option for that, because enable that by default is a breaking change, i think good name for that is `exportGlobals`

**Comment by david-zw-liu** [comment]
> Good job! We need an option for that, because enable that by default is a breaking change, i think good name for that is `exportGlobals`

Hi @evilebottnawi ,
I just added `exportGlobals` option.
Could you please help review this again?

Thanks.

**Review by alexander-akait — APPROVED** [review]
/cc @jquense

**Review by jquense — APPROVED** [review]
LGTM to me, seems like a reasonable option to be able to opt into

**Pull request merged**
