### PR TITLE
[bug fix][add test case] add handle animation short name pattern case

### PR DESCRIPTION
**Pull request by SamXChen**
fix a bug in animation short name pattern like "animation: 2s _colon_local(fade-in);"

### CODE REVIEW

**Comment by Sanford284** [comment]
thank you sam, It works for me.

**Comment by SuperOleg39** [comment]
Hi!

This PR fix problem from [this issue](https://github.com/css-modules/postcss-modules/issues/83)

@SamXChen sorry, can you update this PR, and maybe @evilebottnawi can merge and release it?

**Comment by alexander-akait** [comment]
Need rebase

**Comment by SamXChen** [comment]
> Hi!
> 
> This PR fix problem from [this issue](https://github.com/css-modules/postcss-modules/issues/83)
> 
> @SamXChen sorry, can you update this PR, and maybe @evilebottnawi can merge and release it?

ok, please wait a moment

**Comment by SamXChen** [comment]
> Hi!
> 
> This PR fix problem from [this issue](https://github.com/css-modules/postcss-modules/issues/83)
> 
> @SamXChen sorry, can you update this PR, and maybe @evilebottnawi can merge and release it?

it's ready now

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks!

**Comment by SuperOleg39** [comment]
Thanks)

**Pull request merged**
