### PR TITLE
fix: don't rescope imported names

### PR DESCRIPTION
**Pull request by jquense**
I think i would consider this a fix. But maybe we should communicate more explicitly with the values plugin via `result` 

the idea here is if you have an imported value, that values identifier shouldn't be changed in the places it was replaced other downstream the right values won't work

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Avoid `;` too. 

Also please create issue for coordination in future. Now we have 3 PRs and can potential break other code. We should discussion and merge step by step. No need rush.

**Comment by jquense** [comment]
Sorry @evilebottnawi it's not clear where to open an issue for all of these packages broadly. I did try to bring this up for discussion here: https://github.com/css-modules/postcss-modules-values/pull/2#issuecomment-464125002 sorry if i wasn't clear there 👍

**Comment by jquense** [comment]
it may be worth consolidating a lot of these small plugins into a single postcss-css-modules monorepo

**Comment by alexander-akait** [comment]
@jquense i think it is impossible right now due historical reason, let's solve some architecture problem in plugin first and then we can do this

**Comment by jquense** [comment]
i can, tho I think that i may close this one for a different, better approach. I rather than skipping values, it would be better to not scope them as `:local` in the first place.

**Comment by alexander-akait** [comment]
@jquense :+1: Feel free to do it

**Pull request closed without merging**
